## 每隔3天拉取一次作者脚本到自己仓库的分支
name: faker3-sync-3day
on:
  schedule:
    - cron: '0 0 1/3 * ?'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-faker3
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync faker3-3day
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/shufflewzc/faker3.git"
          source_branch: "main"
          destination_branch: "bak"
          github_token: ${{ secrets.PAT }}
